import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Section,
  Row,
  Column,
  Text,
} from "@react-email/components";

interface PaymentAdminNotificationProps {
  name: string;
  email: string;
  mobile: string;
  productLabel: string;
  amountText: string;
  paymentId: string;
  paidOn: string;
  validTill: string;
}

export default function PaymentAdminNotification({
  name,
  email,
  mobile,
  productLabel,
  amountText,
  paymentId,
  paidOn,
  validTill,
}: PaymentAdminNotificationProps) {
  return (
    <Html>
      <Head />
      <Preview>New payment received</Preview>

      <Body
        style={{
          backgroundColor: "#f5f7fa",
          fontFamily: "Arial, sans-serif",
          padding: "30px 0",
        }}
      >
        <Container
          style={{
            maxWidth: "650px",
            margin: "0 auto",
            backgroundColor: "#ffffff",
            borderRadius: "8px",
            border: "1px solid #e5e7eb",
            padding: "30px",
          }}
        >
          <Heading
            style={{
              color: "#0f172a",
              fontSize: "24px",
              marginBottom: "20px",
            }}
          >
            💰 New Payment Received
          </Heading>

          <Text style={{ color: "#475569", marginBottom: "20px" }}>
            A student has completed a payment on the 2212 website.
          </Text>

          <Section>
            <Row>
              <Column>
                <Text>
                  <strong>Name:</strong> {name}
                </Text>
                <Text>
                  <strong>Email:</strong> {email}
                </Text>
                <Text>
                  <strong>Mobile:</strong> {mobile}
                </Text>
                <Text>
                  <strong>Product:</strong> {productLabel}
                </Text>
                <Text>
                  <strong>Amount:</strong> {amountText}
                </Text>
                <Text>
                  <strong>Payment ID:</strong> {paymentId}
                </Text>
                <Text>
                  <strong>Paid on:</strong> {paidOn}
                </Text>
                <Text>
                  <strong>Valid until:</strong> {validTill}
                </Text>
              </Column>
            </Row>
          </Section>

          <Section
            style={{
              marginTop: "30px",
              borderTop: "1px solid #e5e7eb",
              paddingTop: "20px",
            }}
          >
            <Text style={{ fontSize: "13px", color: "#64748b" }}>
              This email was automatically generated by the 2212 website.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}